/**
 * command/CommandHandler.java
 *
 * File generated from the CommandHandler uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package command;

import repositories.ShipRepository;

public abstract class AbsCommandHandler<T> {
		private T command;
		protected ShipRepository shipRepository;
		
		public AbsCommandHandler(T command, ShipRepository shipRepository) {
			this.command = command;
			this.shipRepository = shipRepository;
		}
		
		public T getCommand() {   return command;	}
		public abstract void execute();
}