/**
 * command/ShipCommand.java
 *
 * File generated from the ShipCommand uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package command;

import java.util.Date;

public abstract class  AbsCommand {
	private String shipId;
	private Date occured;

	protected AbsCommand(String shipId, Date occured){
		this.shipId = shipId;
		this.occured = occured;
	}

	public String getShipId() {	return shipId;}
	public Date getOccured() {	return occured;}
	
}