/**
 * command/ShipArrivalCommand.java
 *
 * File generated from the ShipArrivalCommand uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package command;

import java.util.Date;

import domain.Port;

/**
 * Description of the class ShipArrivalCommand.
 *
 */

public class SetArrivalCommand extends AbsCommand {
		private Port fromPort;
		
		public SetArrivalCommand(String shipId, Date occured, String fromPortCity, String fromPortCountry) {
			super(shipId, occured);
			this.fromPort = new Port(fromPortCity, fromPortCountry);
		}
		
		public Port getFromPort() { return fromPort;}
		
}