/**
 * command/ShipDepartureCommand.java
 *
 * File generated from the ShipDepartureCommand uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package command;

import java.util.Date;

import domain.Port;

/**
 * Description of the class ShipDepartureCommand.
 *
 */

public class SetDepartureCommand extends AbsCommand {
		private Port toPort;
		
		public SetDepartureCommand(String shipId, Date occured, String toPortCity, String toPortCountry) {
			super(shipId, occured);
			this.toPort = new Port(toPortCity, toPortCountry);
		}
		
		public Port getToPort() { return toPort;}
		
}