/**
 * domain/Cargo.java
 *
 * File generated from the Cargo uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package domain;

/**
 * Description of the class Cargo.
 *
 */

public class Cargo {
		private String name;

		public Cargo(String name) {this.name = name;}
		public String getName() {   return name; }
		public void setName(String name) {   this.name = name; }
		
}