/**
 * domain/Ship.java
 *
 * File generated from the Ship uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package domain;

public class Ship {
		private String id;
		private String name;
		private Cargo cargo;
		private Port port;
		
		public Ship(String id, String name, Cargo cargo, Port port) {
			this.id = id;
			this.name = name;
			this.cargo = cargo;
			this.port = port;
		}
		
		public String getId() {	return id;	}
		public void setId(String id) {	this.id = id;}
		public String getName() { return name;}
		public void setName(String name) {    this.name = name;	}
		public Cargo getCargo() {  return cargo;}
		public void setCargo(Cargo cargo) {  this.cargo = cargo;}
		public Port getPort() {    return port;	}
		public void setPort(Port port) {   this.port = port;}
}