/**
 * events/DomainEvent.java
 *
 * File generated from the DomainEvent uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.Date;

import domain.Ship;

public abstract class AbsDomainEvent{
		private Date occured;
		private Date recorded;
		protected Ship ship;
 
		public AbsDomainEvent(Date occured, Ship ship) {
			this.occured = occured;
			this.recorded = new Date();
			this.ship = ship;
		}
		
		public Date getOccured() {  return occured;	}
		public void setOccured(Date occured) { this.occured = occured;}
		public Date getRecorded() {  return recorded;	}
		public void setRecorded(Date recorded) {  this.recorded = recorded;}
		public Ship getShip() {return ship;}
		public void setShip(Ship ship) {this.ship = ship;}

		public abstract void process();
}