/**
 * events/ArrivalShippedEvent.java
 *
 * File generated from the ArrivalShippedEvent uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.Date;

import domain.Port;
import domain.Ship;

public class ArrivalHasBeenSettedEvent extends AbsDomainEvent {
		private Port fromPort;
		
		public ArrivalHasBeenSettedEvent(Date occured, Ship ship, Port fromPort) {
			super(occured, ship);
			this.setFromPort(fromPort);
		}

		public Port getFromPort() {return fromPort;}
		public void setFromPort(Port fromPort) {this.fromPort = fromPort;}

		public void process() {
			getShip().setPort(fromPort);
		}
}