/**
 * events/DepartureShippedEvent.java
 *
 * File generated from the DepartureShippedEvent uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.Date;

import domain.Port;
import domain.Ship;

public class DepartureHasBeenSettedEvent extends AbsDomainEvent {
		private Port toPort;
		
		public DepartureHasBeenSettedEvent(Date occured, Ship ship, Port toPort) {
			super(occured, ship);
			this.toPort = toPort;
		}
		
		public Port getToPort() {return toPort;}
		public void setToPort(Port toPort) {this.toPort = toPort;}

		public void process() {
			ship.setPort(toPort);
		}
}