/**
 * events/DomainEventHandler.java
 *
 * File generated from the DomainEventHandler uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.ArrayList;
import java.util.List;

public class DomainEventHandler {
		private List<AbsDomainEvent> log;
		
		public DomainEventHandler() {
			log = new ArrayList<AbsDomainEvent>();
		}
		
		public List<AbsDomainEvent> getLog() { return log;}
		private void addLog(AbsDomainEvent event) { this.log.add(event);}
		
		public void process(AbsDomainEvent event) {
			addLog(event);
			event.process();
		}
}