/**
 * repositories/ShipRepository.java
 *
 * File generated from the ShipRepository uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package repositories;

import domain.IShipStore;
import domain.Ship;
import events.AbsDomainEvent;
import events.DomainEventHandler;

public class ShipRepository {
	private DomainEventHandler shipEventHandler;
	private IShipStore shipStore;
	
	public ShipRepository(DomainEventHandler shipEventHandler, IShipStore shipStore) {
		this.shipEventHandler = shipEventHandler;
		this.shipStore = shipStore;
	}
		
		public void setShipEventHandler(DomainEventHandler shipEventHandler){ 
			this.shipEventHandler = shipEventHandler;
		}
	
		public void handleEvent(AbsDomainEvent event) {
			shipEventHandler.process(event);
		}

		public Ship getShipById(String shipId) {
			return shipStore.get(shipId);
		}
}